overall test

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -347,9 +347,9 @@ jobs:
               URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-west-2.amazonaws.com/#/employees"            
               if curl -s ${URL} | grep "Welcome"
               then
-              return 1
+              exit 1
               else
-              return 1
+              exit 1
               fi
       - rollback
 
@@ -381,6 +381,15 @@ jobs:
             aws s3 rm s3://udapeople-nanodegfrontend --region us-west-2 --recursive
             aws cloudformation delete-stack --stack-name nanoDegFrontendStack --region us-west-2
             aws cloudformation delete-stack --stack-name nanoDegBackendStack --region us-west-2
+
+  test:
+    docker:
+      - image: amazoe/aws-cli
+    steps:
+      - checkout
+      - run:
+          name: test exit
+          command: echo test exit code $$ exit 1
           
 
 workflows:
@@ -424,35 +433,36 @@ workflows:
       #- new-backend-infrastructure:
       #   requires:
       #     - cloudfront-infrastructure
-      - new-backend-infrastructure
-      - new-frontend-infrastructure
+      #- new-backend-infrastructure
+      #- new-frontend-infrastructure
       #- new-frontend-infrastructure:
       #   requires:
       #     - cloudfront-infrastructure
-      - save-new-backurl:
-         requires:
-           - new-backend-infrastructure
-      - new-backend-config:
-         requires:
-           - new-backend-infrastructure   
-      - db-migrations:
-         requires:
-           - new-backend-config 
-      - upload-backend:
-         requires:
-           - db-migrations
-      - deploy-frontend:
-         requires:
-           - upload-backend
-      - smoketest:
-         requires:
-            - deploy-frontend
-      - promotion:
-         requires:
-           - smoketest
-      - cleanup:
-         requires:
-           - promotion
+      #- save-new-backurl:
+      #   requires:
+      #     - new-backend-infrastructure
+      #- new-backend-config:
+      #   requires:
+      #     - new-backend-infrastructure   
+      #- db-migrations:
+      #   requires:
+      #     - new-backend-config 
+      #- upload-backend:
+      #   requires:
+      #     - db-migrations
+      #- deploy-frontend:
+      #   requires:
+      #     - upload-backend
+      #- smoketest:
+      #   requires:
+      #      - deploy-frontend
+      #- promotion:
+      #   requires:
+      #     - smoketest
+      #- cleanup:
+      #   requires:
+      #     - promotion
+      - test
 
 
            
